server {
    listen 80;
    server_name test-vps.duckdns.org;

    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;

    server_name test-vps.duckdns.org;

    root /var/www/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/test-vps.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/test-vps.duckdns.org/privkey.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {

        fastcgi_pass app:9000;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}