server {
    listen 80;
    server_name 34.165.223.231;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src *; font-src *;";
    add_header X-Content-Type-Options nosniff;

    # منع الـ redirect لـ HTTPS
    proxy_hide_header Upgrade-Insecure-Requests;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}